import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google'
import Script from 'next/script';
import { Providers } from '@/components/Providers';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Generated App',
  description: 'Generated by Zeus',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          {children}
          
        </Providers>
              <Script src="http://localhost:3030/inspector-client.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}